### ISSUE TITLE
希望goscheduler做的越来越好

### ISSUE THREAD

**Issue by pptfz** [gaggad/goscheduler#1]
感谢大佬继续gocron的开发，之前公司一直在使用gocron，之前使用gocron管理了大数据/php/go等相关的任务，管理非常方便
其实我一直有一个疑问，这里这个白框是前端就是这么设计的么？还是说可以给它跟上边连起来😁，不连起来看着感觉怪怪的

![image](https://github.com/user-attachments/assets/faf2b435-c2f4-419e-8442-d7f3894772fa)

**Comment by gaggad** [comment]
感谢支持。我也觉得那个边框有点怪，我把它去掉了，并简单调整了一下一二级标题的位置
![1731286721873_F0A93CD9-F8C2-44df-BCA3-4718D1B6DD45](https://github.com/user-attachments/assets/36da8c8d-d763-46c5-a001-f684ddb3ce52)

**Comment by pptfz** [comment]
@gaggad 个人感觉第二种更好一些，有高亮显示，看起来视觉效果很不错，感谢修改，麻烦问一下具体修改了哪里呢，学习一下😁

**Comment by gaggad** [comment]
@pptfz 可以看下：https://github.com/gaggad/goscheduler/commit/6bd380c5df9daca460fbb4129c8a51b264f0b3a8
