### ISSUE TITLE
任务依赖不生效

### ISSUE THREAD

**Issue by sjdgbhb** [gaggad/goscheduler#2]
创建了两个py任务8和9，需要8执行完了才能执行9，在任务8里配置配置了强依赖，子任务是9
1、将任务9的调度时间设置在当前时间前，任务8手动执行完成后，任务9不会自动执行
2、将任务9的调度时间设置在当前时间后，任务8手动执行，在执行过程中，如果任务9的调度时间到了，任务9会直接执行，也就是说，并没有等待任务8执行完再执行

**Comment by gaggad** [comment]
任务9的类型需要配置为子任务，子任务是不需要设置调度时间的
